spring:
  profiles:
    active:
    - dev
---
spring:
      profiles: dev        
      application:
          name: microservericeloud-config-atguigu-dev
---
spring:
      profiles: test      
      application:
          name: microservericeloud-config-atguigu-test