server:
  port: 7777

spring:
  application:
    name: microservicecloud-config-ribbon-client
  profiles:
    active: dev

eureka:
  client:
    service-url:
        defualtZone: http://localhost:7001/eureka/
  instance:
    hostname: ribbon-7777.com
---
server:
  port: 7777

spring:
  application:
    name: microservicecloud-config-ribbon-client
  profiles:
    active: test
eureka:
  client:
    service-url: 
        defualtZone: http://localhost:7001/eureka/
  instance:
    hostname: ribbon-7777.com

