
spring:
  profiles: 
    active: dev
  application:
    name: microservicecloud-config-dept-client
---
spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-config-dept-client