spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud01?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.Pojo
eureka:
  client:
   service-url:
       defaultZone: http://localhost:7001/eureka/
   instance:
       hostname: dept-8001.com
       prefer-ip-address: true
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud01?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package:  com.example.Pojo
eureka:
  client:
    service-url:
      defualtZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: dept-8001.com
    prefer-ip-address: true