server:
  port: 7001

spring:
  application:
    name: microsevicecloud-config-eureka-client
  profiles:
    active£ºtest
eureka:
  client:
    service-url: 
        defualtZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: false
---
server:
  port: 7001

spring:
  application:
    name: microsevicecloud-config-eureka-client
  profiles: 
    active£ºtest

eureka:
  client:
    service-url: 
        defualtZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: false
