spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client